### ISSUE TITLE
sed in OS X ...

### ISSUE THREAD

**Issue by yannsq** [chadbraunduin/markdown.bash#1]
Hi, 
first, I would like to thank you for this nice script :)
I was looking for a simple way to transform Markdown in HTML but did not wanted to rely on lots of tools and your project just fit perfectly.
I have one issue although because I tried to use it under OS X and the BSD sed is not exactly like the GNU sed. I've installed gnu-sed through brew and slightly modified your script by adding this:

if [ "${OSTYPE}" = "darwin13" ]
  then
  export SED=gsed
else
  export SED=sed
fi

and replaced all occurrences of 'sed' by ${SED}. Now I can happily use it under OS X. I'm not a sed expert and thus do not know if some others options could be used instead of installing gnu-sed. Although, I believe that testing that OSTYPE has 'darwin' for prefix would be better and issuing an error message if 'geed' is not installed ... Anyway, just a really small contribution to your work ;)

Best regards, yann.

**Comment by dgmstuart** [comment]
Hi I'm trying to run it on OSX 10.10 and I get a lot of `sed: illegal option -- r` - I assume this is the same issue?

For those who come after me: the `shopt`/`alias` lines described above are commented out in the top of the file: uncomment those and the script works :)

@chadbraunduin does this warrant a note in the README?

**Comment by chadbraunduin** [comment]
Yes, it does. The README has now updated to include instructions for applying this fix. @dgmstuart, I appreciate the note.

**Comment by dgmstuart** [comment]
@chadbraunduin awesome :)
